# This is required for the API. See https://github.com/Nandaka/PixivUtil2/wiki#pixiv-login-using-cookie
# Please keep this carefully, there is a risk of account theft if somebody got your cookie.
# It is better to use a decoy account, instead of using your main account's cookie.
PHPSESSID: 75921176_zsZa7sNLX8zj4N9UKf526ZV0wdWOwN79

Port: "8080"

UserAgent: Mozilla/5.0

# Number of items in each list page
PageItems: 30

# Default image proxy server. Recommended since Pixiv doesn't like you accessing images on their server.
ImageProxyServer: px2.rainchan.win
