version: "3.7"

services:
  pixivfe:
    container_name: pixivfe
    hostname: pixivfe
    restart: always
    user: 65534:65534
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8282:8080'
    environment:
      - PIXIVFE_TOKEN=changethis